<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Sarina Khajeharzani" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>sarina project1</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">sarina project1</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<script src="../../rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="../../rmarkdown-libs/plotly-binding/plotly.js"></script>
<script src="../../rmarkdown-libs/typedarray/typedarray.min.js"></script>
<script src="../../rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="../../rmarkdown-libs/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="../../rmarkdown-libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/plotly-main/plotly-latest.min.js"></script>


<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE)</code></pre>
<div id="my-project-1" class="section level2">
<h2>My project 1</h2>
</div>
<div id="introduction" class="section level2">
<h2>introduction:</h2>
<p><em>I choose the two data sets (hate_crimes) and (state_info) from the database fivethirtyeight. Both of my datasets have the states name in common and that is how I joined them. I moved to the U.S. about four years ago and I always wanted to learn more about it. The data set state_info has the variables: states name, abbreviations of the states, divion and region of each state. The data set hate_crimes has the variables: states name, abbreviations of the states, the median income of households, how much people do not like crime and the amount of shares of different groups of people.</em></p>
</div>
<div id="joinig-data" class="section level2">
<h2>joinig data:</h2>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(ggplot2)
library(ggridges)
select&lt;-dplyr::select
library(fivethirtyeight)</code></pre>
<pre><code>## Some larger datasets need to be installed separately, like senators and
## house_district_forecast. To install these, we recommend you install the
## fivethirtyeightdata package by running:
## install.packages(&#39;fivethirtyeightdata&#39;, repos =
## &#39;https://fivethirtyeightdata.github.io/drat/&#39;, type = &#39;source&#39;)</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  3.0.4     ✓ purrr   0.3.4
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>write.csv(hate_crimes, &quot;hc.csv&quot;)
getwd()</code></pre>
<pre><code>## [1] &quot;/stor/home/sk49523/website1/content/project&quot;</code></pre>
<pre class="r"><code>hc &lt;- read.csv(&quot;hc.csv&quot;)


write_csv(state_info, &quot;si.csv&quot;)
getwd()</code></pre>
<pre><code>## [1] &quot;/stor/home/sk49523/website1/content/project&quot;</code></pre>
<pre class="r"><code>si &lt;- read.csv(&quot;si.csv&quot;)


fulldata &lt;- full_join(si, hc ,by=&quot;state&quot;) 
fulldata &lt;- fulldata %&gt;% na.omit()

new &lt;- fulldata %&gt;% select(state, &quot;abbrev&quot;= state_abbrev.x, -state_abbrev.y, &quot;income&quot;=median_house_inc, -share_unemp_seas, -share_pop_metro, -share_pop_hs, &quot;noncitizen&quot;=share_non_citizen,&quot;whitep&quot;=share_white_poverty, -gini_index, &quot;nonewhite&quot;=share_non_white, -share_vote_trump, &quot;hatecrime&quot;=hate_crimes_per_100k_splc, &quot;av.hatecrime&quot;=avg_hatecrimes_per_100k_fbi, division,region)</code></pre>
<p><em>I used full_join for joining my two data sets to have all of my variables and I used the common variable state for joining them. I also made a new data called “new” from fulldata in which I dropped the variables share_vote_trump, gini_index, share_pop_metro, share_pop_hs, share_unemp_seas. I do not think this should be a problem because I had too many variables and wanted to decrease them and I have the fulldata intact in case I needed to use the whole data in any step.</em></p>
</div>
<div id="tidy-data" class="section level2">
<h2>tidy data:</h2>
<pre class="r"><code>library(tidyverse)
library(dplyr)
#untidy &lt;- new  %&gt;% pivot_wider(names_from=&quot;region&quot;, values_from=&quot;whitep&quot;) 
#tidy &lt;- untidy%&gt;% pivot_longer(c(&quot;South&quot;, &quot;West&quot;, &quot;Northeast&quot;, &quot;Midwest&quot;), names_to=&quot;regions&quot;,values_to=&quot;whitep&quot;) %&gt;% na.omit()</code></pre>
<p><em>My data were already tidy therefore I tried to untidy and tidy my data again. I used pivot_wider function for un-tiding my data and pivot_wider for tiding my data again.</em></p>
<p>##summary satistics</p>
<pre class="r"><code>new %&gt;% arrange(desc(income)) %&gt;% filter(region==&quot;South&quot;) %&gt;% select(1:8)  %&gt;% mutate(sum= (nonewhite)+ (whitep))</code></pre>
<pre><code>##                   state abbrev income noncitizen whitep nonewhite  hatecrime
## 1              Maryland     MD  76165       0.08   0.06      0.50 0.37043897
## 2  District of Columbia     DC  68277       0.11   0.04      0.63 1.52230172
## 3              Virginia     VA  66155       0.06   0.07      0.38 0.36324890
## 4              Delaware     DE  57522       0.05   0.08      0.37 0.32275417
## 5                 Texas     TX  53875       0.11   0.08      0.56 0.21358394
## 6               Georgia     GA  49555       0.08   0.09      0.48 0.12042027
## 7              Oklahoma     OK  47199       0.04   0.10      0.35 0.13362910
## 8        North Carolina     NC  46784       0.05   0.10      0.38 0.24400659
## 9               Florida     FL  46140       0.09   0.11      0.46 0.18752122
## 10       South Carolina     SC  44929       0.03   0.09      0.36 0.20989442
## 11             Arkansas     AR  44922       0.04   0.12      0.26 0.06906077
## 12            Tennessee     TN  43716       0.04   0.13      0.27 0.19993848
## 13             Kentucky     KY  42786       0.03   0.17      0.15 0.32439697
## 14            Louisiana     LA  42406       0.02   0.12      0.42 0.10973335
## 15              Alabama     AL  42278       0.02   0.12      0.35 0.12583893
## 16        West Virginia     WV  39552       0.01   0.14      0.07 0.32867707
##    av.hatecrime  sum
## 1     1.3248395 0.56
## 2    10.9534797 0.67
## 3     1.7247546 0.45
## 4     1.4699796 0.45
## 5     0.7527683 0.64
## 6     0.4120118 0.57
## 7     1.0816721 0.45
## 8     1.2626798 0.48
## 9     0.6980703 0.57
## 10    1.9370828 0.45
## 11    0.8692089 0.38
## 12    3.1360512 0.40
## 13    4.2078896 0.32
## 14    1.3411696 0.54
## 15    1.8064105 0.47
## 16    2.0370536 0.21</code></pre>
<pre class="r"><code>new %&gt;% summarize_all(n_distinct)</code></pre>
<pre><code>##   state abbrev income noncitizen whitep nonewhite hatecrime av.hatecrime
## 1    45     45     45         12     12        32        45           45
##   division region
## 1        9      4</code></pre>
<pre class="r"><code>new %&gt;% group_by(state, region) %&gt;% summarize_all(n_distinct)</code></pre>
<pre><code>## # A tibble: 45 x 10
## # Groups:   state [45]
##    state region abbrev income noncitizen whitep nonewhite hatecrime av.hatecrime
##    &lt;fct&gt; &lt;fct&gt;   &lt;int&gt;  &lt;int&gt;      &lt;int&gt;  &lt;int&gt;     &lt;int&gt;     &lt;int&gt;        &lt;int&gt;
##  1 Alab… South       1      1          1      1         1         1            1
##  2 Alas… West        1      1          1      1         1         1            1
##  3 Ariz… West        1      1          1      1         1         1            1
##  4 Arka… South       1      1          1      1         1         1            1
##  5 Cali… West        1      1          1      1         1         1            1
##  6 Colo… West        1      1          1      1         1         1            1
##  7 Conn… North…      1      1          1      1         1         1            1
##  8 Dela… South       1      1          1      1         1         1            1
##  9 Dist… South       1      1          1      1         1         1            1
## 10 Flor… South       1      1          1      1         1         1            1
## # … with 35 more rows, and 1 more variable: division &lt;int&gt;</code></pre>
<pre class="r"><code>new %&gt;% summarize_if(is.numeric, list(min=min, max=max, sd=sd, median=median, mean=mean) , na.rm=T)</code></pre>
<pre><code>##   income_min noncitizen_min whitep_min nonewhite_min hatecrime_min
## 1      39552           0.01       0.04          0.06    0.06906077
##   av.hatecrime_min income_max noncitizen_max whitep_max nonewhite_max
## 1        0.4120118      76165           0.13       0.17          0.63
##   hatecrime_max av.hatecrime_max income_sd noncitizen_sd  whitep_sd
## 1      1.522302         10.95348  8979.492    0.03123227 0.02466339
##   nonewhite_sd hatecrime_sd av.hatecrime_sd income_median noncitizen_median
## 1    0.1486936    0.2515628        1.718622         54916              0.05
##   whitep_median nonewhite_median hatecrime_median av.hatecrime_median
## 1          0.09              0.3        0.2261971            1.937083
##   income_mean noncitizen_mean whitep_mean nonewhite_mean hatecrime_mean
## 1    55299.49      0.05533333  0.09088889      0.3175556        0.30243
##   av.hatecrime_mean
## 1          2.373812</code></pre>
<pre class="r"><code>new %&gt;% group_by(state, region) </code></pre>
<pre><code>## # A tibble: 45 x 10
## # Groups:   state, region [45]
##    state abbrev income noncitizen whitep nonewhite hatecrime av.hatecrime
##    &lt;fct&gt; &lt;fct&gt;   &lt;int&gt;      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Alab… AL      42278       0.02   0.12      0.35    0.126         1.81 
##  2 Alas… AK      67629       0.04   0.06      0.42    0.144         1.66 
##  3 Ariz… AZ      49254       0.1    0.09      0.49    0.225         3.41 
##  4 Arka… AR      44922       0.04   0.12      0.26    0.0691        0.869
##  5 Cali… CA      60487       0.13   0.09      0.61    0.256         2.40 
##  6 Colo… CO      60940       0.06   0.07      0.31    0.391         2.80 
##  7 Conn… CT      70161       0.06   0.06      0.3     0.335         3.77 
##  8 Dela… DE      57522       0.05   0.08      0.37    0.323         1.47 
##  9 Flor… FL      46140       0.09   0.11      0.46    0.188         0.698
## 10 Geor… GA      49555       0.08   0.09      0.48    0.120         0.412
## # … with 35 more rows, and 2 more variables: division &lt;fct&gt;, region &lt;fct&gt;</code></pre>
<pre class="r"><code>new%&gt;% summarize(means= mean(income))</code></pre>
<pre><code>##      means
## 1 55299.49</code></pre>
<p><em>for the summary statistics first I used arrange and the function descending to arrange my data in a way that I have the highest income on the top of my table and then the lower ones.I used filter to only select the data that are in the South region and then the function select to remove the unnecessary columns. with mutate I created a new column called sum which has the addition of shares of the people who are not white and people who are white and in poverty. I specificity used suumarize_if because I only wanted to calculate the summary statistics of the numeric variables not everything. From the data we can see that the division South Atlantic in the region south has the highest income and among thoese Maryland with 76165 has the highest income of all. The min income of house holds is West Virginia with the income 39552. Something that was interesting from my data was that even though U.S. has 51 states my distinct number of states in my data was 45. </em></p>
</div>
<div id="graph" class="section level2">
<h2>graph</h2>
<pre class="r"><code>#new %&gt;% select_if(is.numeric) %&gt;% cor %&gt;% as.data.frame %&gt;% rownames_to_column %&gt;% pivot_longer(-1) %&gt;%ggplot(aes(rowname,name,fill=value))+geom_tile()geom_text(aes(label=round(value,2)))+ xlab(&quot;&quot;)+ylab(&quot;&quot;)+coord_fixed()+scale_fill_gradient2(low=&quot;red&quot;,mid=&quot;white&quot;,high=&quot;blue&quot;)+ theme_minimal()+ ggtitle(&quot;graph1&quot;) </code></pre>
<p><em>In graph1 we can see the correlation head map of the numeric variables in the data set new. I choose the data set new instead of fulldata because the names were shorter and it has less data which resulted in a better graph. In this graph the strongest correlation is 1 between each variable and itself. The next strongest correlation was -0.81 between income and white poverty meaning that the white poverty group had the lowest income.The smallest correlation is 0.04 between income and nonwhite meaning that according to this data there is no a strong relationship between income and people who are not white.</em></p>
<pre class="r"><code>#graph2
#new %&gt;% ggplot(aes(region,income)) + facet_wrap(~division) + geom_bar(stat=&quot;summary&quot;) + geom_errorbar(stat=&quot;summary&quot;, col=&quot;red&quot;)+ theme_minimal()+ ggtitle(&quot;graph2&quot;) </code></pre>
<p><em>In graph2 we can wee a visualization of the income in different regions and divisions. From the graph it is clear that New England, region northeast has the highest income. The East South Central in the South has the lowest income. South Atlantic, has the widest error bar and East South Central has the smallest error bar.</em></p>
<pre class="r"><code>ggplot(new, aes(x= income , y= region)) +geom_point(size=2,alpha=.8, aes(color=hatecrime))+coord_flip()+ theme_minimal()</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><em>I thought graph3 was interesting because in addition to showing the income of different regions it is also showing how much people hate crime in these areas. According to the graph it can be concluded that most of people have a low income and they do not like crime so maybe a crime is a major issue in that are. We even have the brightest point in the south which represents in the highest number for disliking crime.</em></p>
</div>
<div id="cluster" class="section level2">
<h2>Cluster</h2>
<pre class="r"><code>library(cluster)
select&lt;-dplyr::select


#way 1
clust_data &lt;- new %&gt;% select(noncitizen, nonewhite , income)
set.seed(348)
kmeans1 &lt;- clust_data %&gt;% kmeans(2)
kmeans1$cluster</code></pre>
<pre><code>##  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 20 21 22 23 25 26 27 28 29 
##  1  2  1  1  2  2  2  2  1  1  1  1  1  2  1  1  1  2  2  1  2  2  1  2  1  2 
## 30 31 32 33 35 36 37 38 39 40 42 43 44 45 46 47 48 49 51 
##  2  1  1  1  1  1  2  1  2  1  1  1  2  2  2  2  1  2  2</code></pre>
<pre class="r"><code>#save the cluster solution in your dataset
kmeansclust &lt;- clust_data %&gt;% mutate (cluster= as.factor( kmeans1$cluster )) 
kmeansclust %&gt;%ggplot(aes(noncitizen, nonewhite , income, color=cluster))+geom_point() </code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>pam1&lt;- clust_data %&gt;% pam(2)
pam1</code></pre>
<pre><code>## Medoids:
##    ID noncitizen nonewhite income
## 33 30       0.05      0.38  46784
## 47 42       0.08      0.31  59068
## Clustering vector:
##  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 20 21 22 23 25 26 27 28 29 
##  1  2  1  1  2  2  2  2  1  1  2  2  1  2  2  1  1  2  2  1  2  2  1  2  1  2 
## 30 31 32 33 35 36 37 38 39 40 42 43 44 45 46 47 48 49 51 
##  2  1  2  1  1  1  2  2  2  1  1  2  2  2  2  2  1  2  2 
## Objective function:
##    build     swap 
## 5002.200 4076.156 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
<pre class="r"><code>plot(pam1, which=2)</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code>#way 2
#choosing the best k for three variables
pam_dat&lt;- new %&gt;% select(noncitizen, nonewhite , income)
sil_width&lt;- vector()
for(i in 2:10){
  pam_fit &lt;- pam(pam_dat, k = i)
  sil_width[i] &lt;- pam_fit$silinfo$avg.width
}
ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name=&quot;k&quot;,breaks=1:10)</code></pre>
<pre><code>## Warning: Removed 1 row(s) containing missing values (geom_path).</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-8-3.png" width="672" /></p>
<pre class="r"><code># k=2 is the best according to the graph becasue of its highest number on graph.

#for three variables
library(tidyverse)
library(plotly)</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<pre class="r"><code>pam2&lt;- new  %&gt;% select(noncitizen, nonewhite , income) %&gt;% scale %&gt;% pam(2)
pam2</code></pre>
<pre><code>## Medoids:
##    ID noncitizen  nonewhite     income
## 16 15 -0.4909452 -0.4543271 -0.2066363
## 32 29  1.4301448  0.6889632 -0.1101943
## Clustering vector:
##  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 20 21 22 23 25 26 27 28 29 
##  1  1  2  1  2  1  1  1  2  2  1  2  1  1  1  1  1  2  2  1  1  1  1  1  2  1 
## 30 31 32 33 35 36 37 38 39 40 42 43 44 45 46 47 48 49 51 
##  2  2  2  1  1  1  1  1  2  1  1  2  1  1  1  2  1  1  2 
## Objective function:
##    build     swap 
## 1.205143 1.205143 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
<pre class="r"><code>plot(pam2, which=2)</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-8-4.png" width="672" /></p>
<pre class="r"><code>#accorfing to the graph we get 0.36 which means that the structure is weak and could be artificial.

#graph3d for three variables
final &lt;- new  %&gt;% select(state,noncitizen, nonewhite , income) %&gt;% mutate(cluster=pam2$clustering)

#summarizing the cluster:
final  %&gt;% group_by(cluster)  %&gt;% summarize_if(is.numeric, mean, na.rm=T)</code></pre>
<pre><code>## # A tibble: 2 x 4
##   cluster noncitizen nonewhite income
##     &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
## 1       1     0.0367     0.245 54428.
## 2       2     0.0927     0.463 57042.</code></pre>
<pre class="r"><code>final %&gt;% plot_ly (x= ~noncitizen, y= ~nonewhite , z= ~income, color= ~cluster, type= &quot;scatter3d&quot;, mode=&quot;markers&quot;, symbols= c(&#39;circle&#39;,&#39;x&#39;,&#39;o&#39;))</code></pre>
<pre><code>## Warning: `arrange_()` is deprecated as of dplyr 0.7.0.
## Please use `arrange()` instead.
## See vignette(&#39;programming&#39;) for more help
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<div id="htmlwidget-1" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"visdat":{"12ff014202b1b":["function () ","plotlyVisDat"]},"cur_data":"12ff014202b1b","attrs":{"12ff014202b1b":{"x":{},"y":{},"z":{},"mode":"markers","color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"symbols":["circle","x","o"],"type":"scatter3d"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"noncitizen"},"yaxis":{"title":"nonewhite"},"zaxis":{"title":"income"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"showSendToCloud":false},"data":[{"x":[0.02,0.04,0.1,0.04,0.13,0.06,0.06,0.05,0.09,0.08,0.04,0.07,0.03,0.03,0.04,0.03,0.02,0.08,0.09,0.04,0.05,0.02,0.01,0.05,0.1,0.03,0.11,0.06,0.1,0.05,0.03,0.04,0.07,0.03,0.08,0.03,0.04,0.11,0.04,0.01,0.06,0.08,0.01,0.03,0.11],"y":[0.35,0.42,0.49,0.26,0.61,0.31,0.3,0.37,0.46,0.48,0.16,0.37,0.2,0.15,0.25,0.15,0.42,0.5,0.27,0.24,0.18,0.2,0.1,0.21,0.5,0.09,0.44,0.62,0.42,0.38,0.21,0.35,0.26,0.24,0.28,0.36,0.27,0.56,0.19,0.06,0.38,0.31,0.07,0.22,0.63],"z":[42278,67629,49254,44922,60487,60940,70161,57522,46140,49555,53438,54916,48060,57810,53444,42786,42406,76165,63151,52005,67244,56630,51102,56870,49875,73397,65243,46686,54310,46784,49644,47199,58875,55173,58633,44929,43716,53875,63383,60708,66155,59068,39552,58080,68277],"mode":"markers","type":"scatter3d","marker":{"colorbar":{"title":"cluster","ticklen":2},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,2,1,2,1,1,1,2,2,1,2,1,1,1,1,1,2,2,1,1,1,1,1,2,1,2,2,2,1,1,1,1,1,2,1,1,2,1,1,1,2,1,1,2],"line":{"colorbar":{"title":"","ticklen":2},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,2,1,2,1,1,1,2,2,1,2,1,1,1,1,1,2,2,1,1,1,1,1,2,1,2,2,2,1,1,1,1,1,2,1,1,2,1,1,1,2,1,1,2]}},"frame":null},{"x":[0.01,0.13],"y":[0.06,0.63],"type":"scatter3d","mode":"markers","opacity":0,"hoverinfo":"none","showlegend":false,"marker":{"colorbar":{"title":"cluster","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"color":[1,2],"line":{"color":"rgba(255,127,14,1)"}},"z":[39552,76165],"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code>#graph2d for three variables
ggplot(final, aes(x=noncitizen, y= nonewhite ,z=income , color= cluster))+geom_point()</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-8-6.png" width="672" /></p>
<p><em>For this part of the assignment I choose the three variables of the share of non citizens, share of people who are not white and median income of households. One of the most importent steps was to choose the best k for my three variables and therefore as recommended in the class I plotted a ggplot for K to see which K value has the highest value. According to my graph K=2 has the highest value and that is why I choose the number2. From the next plot I found that the average width is 0.36 which is less than 0.5 and since this number is small we can conclude that the structure is weak and could be artificial.</em></p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
